// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Areas.Admin.Data;

namespace WebApp.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApp.Areas.Admin.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<long>("Thanhtien")
                        .HasColumnType("bigint");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaCTHD");

                    b.HasIndex("MaHD");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.ChuDe", b =>
                {
                    b.Property<int>("MaChuDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Tenchude")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChuDe");

                    b.ToTable("ChuDe");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GiamGia")
                        .HasColumnType("int");

                    b.Property<int?>("HoaDonMaHD")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaylap")
                        .HasColumnType("datetime2");

                    b.Property<long>("TongTien")
                        .HasColumnType("bigint");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHD");

                    b.HasIndex("HoaDonMaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKhuyenMai");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.KhachHang", b =>
                {
                    b.Property<int>("MaNVBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("HinhDaiDien")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HoTenNVBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNVBan");

                    b.HasIndex("MaND");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.KhuyenMai", b =>
                {
                    b.Property<int>("Makhuyenmai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Tenkhuyenmai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Makhuyenmai");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.LoaiSP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenloaiSP")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoaiSP");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhanQuyen")
                        .HasColumnType("int");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SĐT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NhaCC");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhanVienBanHang", b =>
                {
                    b.Property<int>("MaNVBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNVBan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNVBan");

                    b.HasIndex("MaND");

                    b.ToTable("NhanVienBanHang");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhanVienGiaoHang", b =>
                {
                    b.Property<int>("MaNVGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNVGiao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNVGiao");

                    b.HasIndex("MaND");

                    b.ToTable("NhanVienGiaoHang");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhanVienQuanLi", b =>
                {
                    b.Property<int>("MaNVQuanLi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("HinhDaiDien")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("HoTenNVQuanLi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNVQuanLi");

                    b.HasIndex("MaND");

                    b.ToTable("NhanVienQuanLi");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("DonGia")
                        .HasMaxLength(100000000)
                        .HasColumnType("bigint");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaNCC")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Mã loại")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaNCC");

                    b.HasIndex("Mã loại");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.TinTuc", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChuDe")
                        .HasColumnType("int");

                    b.Property<int>("Matacgia")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tentieude")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TrangThai")
                        .HasMaxLength(1000)
                        .HasColumnType("int");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("MaChuDe");

                    b.HasIndex("Matacgia");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("WebApp.Areas.Admin.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Areas.Admin.Models.SanPham", "SanPham")
                        .WithMany("LstCTHD")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.HoaDon", b =>
                {
                    b.HasOne("WebApp.Areas.Admin.Models.HoaDon", null)
                        .WithMany("LstHoaHon")
                        .HasForeignKey("HoaDonMaHD");

                    b.HasOne("WebApp.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany("LstHD")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Areas.Admin.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("LstHoaHon")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.KhachHang", b =>
                {
                    b.HasOne("WebApp.Areas.Admin.Models.NguoiDung", "NguoiDung")
                        .WithMany("LstKH")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhanVienBanHang", b =>
                {
                    b.HasOne("WebApp.Areas.Admin.Models.NguoiDung", "NguoiDung")
                        .WithMany("LstNVBan")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhanVienGiaoHang", b =>
                {
                    b.HasOne("WebApp.Areas.Admin.Models.NguoiDung", "NguoiDung")
                        .WithMany("LstNVGiao")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhanVienQuanLi", b =>
                {
                    b.HasOne("WebApp.Areas.Admin.Models.NguoiDung", "NguoiDung")
                        .WithMany("LstNVQuanli")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.SanPham", b =>
                {
                    b.HasOne("WebApp.Areas.Admin.Models.NhaCungCap", "NCC")
                        .WithMany("LstSanPham")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Areas.Admin.Models.LoaiSP", "Loai")
                        .WithMany("LstSanPham")
                        .HasForeignKey("Mã loại");

                    b.Navigation("Loai");

                    b.Navigation("NCC");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.TinTuc", b =>
                {
                    b.HasOne("WebApp.Areas.Admin.Models.ChuDe", "ChuDe")
                        .WithMany("LstTinTuc")
                        .HasForeignKey("MaChuDe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Areas.Admin.Models.NhanVienQuanLi", "NhanVienQuanLi")
                        .WithMany("LstTinTuc")
                        .HasForeignKey("Matacgia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");

                    b.Navigation("NhanVienQuanLi");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.ChuDe", b =>
                {
                    b.Navigation("LstTinTuc");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.HoaDon", b =>
                {
                    b.Navigation("LstHoaHon");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.KhachHang", b =>
                {
                    b.Navigation("LstHD");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.KhuyenMai", b =>
                {
                    b.Navigation("LstHoaHon");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.LoaiSP", b =>
                {
                    b.Navigation("LstSanPham");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NguoiDung", b =>
                {
                    b.Navigation("LstKH");

                    b.Navigation("LstNVBan");

                    b.Navigation("LstNVGiao");

                    b.Navigation("LstNVQuanli");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhaCungCap", b =>
                {
                    b.Navigation("LstSanPham");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.NhanVienQuanLi", b =>
                {
                    b.Navigation("LstTinTuc");
                });

            modelBuilder.Entity("WebApp.Areas.Admin.Models.SanPham", b =>
                {
                    b.Navigation("LstCTHD");
                });
#pragma warning restore 612, 618
        }
    }
}
